### ISSUE TITLE
Missing C++ banner on top of code box

### ISSUE THREAD

**Issue by stwunsch** [CMSDAS/root-short-exercise#23]
We miss the small banner showing the language, such as for Python or also bash:

![Screenshot from 2020-08-20 11-34-08](https://user-images.githubusercontent.com/6951222/90753665-297c1600-e2d9-11ea-9046-f4a8dae612e6.png)

**Comment by stwunsch** [comment]
@clelange You have an idea how this comes? Not a big deal though. I would just leave it as it is if you have no solution right away.

**Comment by stwunsch** [comment]
I've tried `'''cpp` and `'''c++`, but also `'''c` (ofc the other ticks) does not show up there (even though the code markup itself works).

**Comment by clelange** [comment]
I think this needs some patching at https://github.com/CMSDAS/root-short-exercise/blob/gh-pages/assets/css/lesson.scss#L43-L73

and possibly also at https://github.com/CMSDAS/root-short-exercise/blob/gh-pages/bin/lesson_check.py#L74-L87

**Comment by stwunsch** [comment]
There we go! Thanks for your help :)

![Screenshot from 2020-08-20 12-20-05](https://user-images.githubusercontent.com/6951222/90758579-8b3f7e80-e2df-11ea-9486-0b884763297d.png)
