### ISSUE TITLE
Proposals for additional parts in section 4

### ISSUE THREAD

**Issue by stwunsch** [CMSDAS/root-short-exercise#5]
- THStack
- TRatioPlot
- TEfficiency

**Comment by stwunsch** [comment]
@eguiraud We already cover an extensive amount of features, you think it's too much to add another part in section 4 about the features mentioned above?

**Comment by eguiraud** [comment]
Probably yes, but it would be great if the ROOT manual had sections that we can point to. If it does not, we should open issues
